arch: amd64          # optional, this is default, routes to a full VM
os: linux            # optional, this is default
dist: focal          # or bionic | xenial | trusty | precise with xenial as default

before_install:
  - sudo apt update
  - sudo apt install git

install:
  - git clone https://github.com/ardupilot/ardupilot.git
  - cd ardupilot
  - ./Tools/environment_install/install-prereqs-ubuntu.sh
  #- git checkout Plane-4.1
  - git submodule update --init --recursive

script:
  - ./waf configure --board=blue
  - ./waf

#after_script:
#  #- tree
#  # doxygen docu generation
#  - doxygen Doxyfile >> doxygen.log
#  #- pushd $PWD/doc/latex/; make; popd
#  # push result back to git repo
#  - git checkout -b result/docu
#  #- git add $PWD/doc/
#  - git add --all  # may be use .gitignore to exclude .pyc files (not many yet)
#  #- git status
#  - git config user.email 'travis@travis-ci.org'
#  - git config user.name 'Travis CI'
#  - git commit --message "Travis build $TRAVIS_BUILD_NUMBER" --quiet
#  - git push -f https://$GIT_USER:$GIT_PASS@github.com/drtrigon/sketchbook.git result/docu  # dangerous; overwrite remote branch! may expose password!
#
#after_success:
#  # trigger docker-sketchbook (same tests based on docker-arduino)
#  - |-
#    if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]] ; then
#      if [[ "$DOCKERTAG" == "$LATEST" ]] ; then
#        curl -s -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Travis-API-Version: 3" -H "Authorization: token $TRAVIS_TOKEN" -d "{\"request\": {\"branch\":\"master\"}}" https://api.travis-ci.org/repo/drtrigon%2Fdocker-sketchbook/requests ;
#      fi ;
#    fi

#notifications:
#  email:
#    on_success: change
#    on_failure: change
